### PR TITLE
Add support for Arrays

### PR DESCRIPTION
**Pull request by D0m3-**
I added support for Arrays.

I also changed the signature of prepareUrl to pass the node.

Feel free to use

### CODE REVIEW

**Comment by graysonhicks** [comment]
Thanks @D0m3- !  Does this support using gatsby-source-graphql as well?

**Comment by D0m3-** [comment]
This is all my changes, so I published another npm repo so I could use it directly (I needed support for arrays).
So you don't want to merge the changes in package.json

Probably you don't want the breaking change in prepareUrl either.

Other than that I mostly copied the code that was used and tweaked it for arrays. I had to use a new type option to specify if it's array or object because I didn't know how else to know that in the resolver.

I have no idea if it supports gatsby-source-graphql

**Comment by graysonhicks** [comment]
Thanks @D0m3- .  Looks good to me.  I will try to merge and release as soon as possible.

**Comment by graysonhicks** [comment]
Hey @D0m3- I was looking at this again and have a question.  What does the data structure look like for the nodes you are using?  Is the final node leaf of images an array?  Like this:

```javascript
{
  type: 'myNode',
  id: 1,
  // The imageUrl option needs to support this array instead of a string.
  remoteImageField: [
   'http://remoteImage.com/image.jpg',
   'http://remoteImage.com/image2.jpg',
  ]
}
```

**Comment by D0m3-** [comment]
Hi @graysonhicks 
Yes I think that's correct (been a while).
If you want I can rework this a little bit at some point during the weekend so you don't have to remove some of the extra changes I made

**Comment by graysonhicks** [comment]
@D0m3- That would be great, especially if it is adding support for an array of images at the leaf node.  There are two places that users want array functionality.  First is along the path **_to_** to the leaf node.  For example, in the options:

```javascript
{
  nodeType: 'myNodes'
  imagePath: 'branch.arrayNodes[].imageUrl
}
```

This currently works and is fully described [here](https://github.com/graysonhicks/gatsby-plugin-remote-images#traversing-objects-with-arrays).

Unfortunately, this does not solve the other use case where people want array support, which is at the leaf node itself..  For example:

```javascript
{
  nodeType: 'myNodes'
  imagePath: 'branch.path.imageUrls[]
}
```

In this case, one node has multiple image urls that need to be fetched and attached to the node as `localImages` (plural) instead of `localImage`.  This is the use case we need to solve for.  I think that is what your PR is doing with the `type: 'array'` option, but I wanted to be sure.

Hopefully that clears it up and that that is what this PR accomplishes.

Thanks!

**Comment by D0m3-** [comment]
@graysonhicks see #52, I cleaned it up, or feel free to reuse my branch
You can see how I'm using it there: https://github.com/D0m3-/makramonde/blob/849819f8a22616721740d6a89b323725c0e9de6f/gatsby-config.js#L25

**Pull request closed without merging**
