### PR TITLE
Add prepareUrl option for adjusting the image url if needed

### PR DESCRIPTION
**Pull request by estien**

### CODE REVIEW

**Comment by graysonhicks** [comment]
Hi @estien !  Thanks for preparing this!  Could you describe a use case where this is needed?  Thanks!

**Comment by estien** [comment]
No problem @graysonhicks , and thanks for your plugin.

**Use case**

When pulling data from a third-party API not controlled by the developer of the GatsbyJS site, and said data contains elements with image URLs needing modification prior to being fetched by your plugin, the function `prepareUrl` comes in handy.

Assume that you have data stored in GraphQL somehow as follows:
```json
[
  { "id": 1, "imageUrl": "//example.com/image1.png"},
  { "id": 2, "imageUrl": "https://example.com/image2.png"},
  { "id": 3, "imageUrl": "https://example.com/not-found.png"}
]
```

The first element contains an invalid URL seen from the function `createRemoteFileNode` perspective, as it will fail with the missing HTTP protocol prefix. A reasonable implementation for the `prepareUrl` function to handle the case would be like so:

```javascript
function prepareUrl(url) {
  if (url.startsWith('//')) {
    return `https:${url}`;
  }
  // no modifications are desirable
  return url;
}
```

The second element comes with an `imageUrl` as expected, so no adjustment to the `prepareUrl` function needs to be done.

For the third and last element, let's imagine that it is desirable to replace the not found image with our own. A naive implementation to handle element one and three could be like so:

```javascript
function prepareUrl(url) {
  if (url.startsWith('//')) {
    return `https:${url}`;
  }
  if (url.indexOf('not-found') > -1) {
    return 'https://my-controlled-domain.example.com/not-found.png';
  }
  // no modifications are desirable
  return url;
}
```

We can debate whether the adjustment of the image URLs should be done prior to being stored into GraphQL in the first place, but in some cases (my case at least) both the original and the modified URLs are desirable.

**Comment by graysonhicks** [comment]
Hey @estien , I think this makes sense.  I don't think it will be too common of a use case, but it is an optional param and only a few, readable lines added to `gatsby-node`.  Could you fix the merge conflicts so I can merge in?  Thanks!

**Comment by estien** [comment]
Ok, great. resolved the merge conflicts and pushed to my master branch. However, it is not being picked up here on the PR. Assuming it has something to do with the newly created develop branch? I originally created the PR towards your master. Any idea on how to fix @graysonhicks ?

**Pull request merged**
