### PR TITLE
fix: resolve array managment

### LINKED ISSUE #57: Traversing array not working
Hi, it looks to me as if in the current version 2.2.0, traversing array nodes does not seem to be working. The following works in version 1.0.7:
`gatsby-config.js`:
```javascript
{
      resolve: 'gatsby-plugin-remote-images',
      options: {
        nodeType: 'PictureCollection',
        imagePath: 'pictures[].url',
        name: 'imageSharp',
      }
    }
```
`gatsby-node.js`:
```javascript
exports.sourceNodes = ({ actions, createNodeId, createContentDigest }) => {
  const { createNode } = actions
  createNode({
    id: createNodeId("testNode1"),
    pictures: [
      { url: "https://unsplash.com/photos/aJnHSrgSWkk/download?force=true" },
      { url: "https://unsplash.com/photos/_qy3tHmhwvk/download?force=true" },
      { url: "https://unsplash.com/photos/k3jEtUmKhJo/download?force=true" },
    ],
    internal: {
      type: "PictureCollection",
      contentDigest: createContentDigest({}),
    },
  })
}
```
So I'm creating a node type `PictureCollection` with an array of `pictures` containing objects with `url`s for `gatsby-plugin-remote-images`. In v1.0.7, this creates new `imageSharp` fields on the `pictures` containing exactly the right data for each picture.

In v2.2.0, a single `imageSharp` field is created on the top level of `PictureCollection` instead, with a value of `null`. There does not seem to be a possibility to query the downloaded images.

I believe this is similar to this issue: https://github.com/graysonhicks/gatsby-plugin-remote-images/issues/37, which is however marked as fixed. Am I doing something wrong or is this still broken?

### PR DESCRIPTION
**Pull request by digitalLumberjack**
Hello, i just found this plugin and : thank you.

I found two bugs about path containing an array like `images[].url` :

Tried to fix that by:
- fixing the resolver that resolved a file in place of an array
- fixing the asynchronous bug with the cache when creating nodes from a path containing an array

Not sure about what was the intention of setting the current node and not the ancestor when traversing nodes, I referred the root node as parentRootId.

May fix #57

### CODE REVIEW

**Comment by graysonhicks** [comment]
Hi @digitalLumberjack thanks for the PR.  I'll get this merged in. Long term, I'll probably be deprecating the whole library in favor using the new gatsby-image component, but fixing this will be nice to have!

**Comment by digitalLumberjack** [comment]
Interesting, I did not found how to use dynamic remote image with gatsby-image-plugin.

I'm getting my images url from a parse server, so they are added in a graphql type, and I use gatsby-plugin-remote-images to be able to download and query them with gatsby image in graphql.

Can you give me a clue about how i can do that with the current gatsby-plugin-image without your plugin ?

**Comment by ar7hur** [comment]
@digitalLumberjack thanks for the fix!
If you find a way to use gatsby-plugin-image directly as suggested by @graysonhicks, I'm interested too. As far as I understand, for dynamic images the new plugin still requires a File node to be present. So we need something that turns an url into a File node. Maybe we should write a small plugin that does just that.

**Comment by poopsplat** [comment]
Ditto @digitalLumberjack + @ar7hur comment re: dynamic images in gatsby-plugin-image. Would love to see this PR merged for the time being at least 🙏

**Comment by graysonhicks** [comment]
Hey all, sorry I've been busy, should be able to merge and release this tomorrow!

**Comment by graysonhicks** [comment]
Merged and released with `2.3.0`.  Thanks again @digitalLumberjack !  Hope to see yall online at GatsbyConf tomorrow!

**Pull request merged**
