### PR TITLE
feat(silent): option to silence image load errors

### PR DESCRIPTION
**Pull request by stevensacks**
Added a `silent` option so that image load errors can be silenced.

This is something I needed in my project since hundreds among the thousands of images my site do not load because they've been removed, etc. The team in charge of managing the images and urls doesn't always properly clean things up.

Without this option, the console gets flooded with errors.

This change is very small and does not affect the functionality of the plugin, just the `console.error()` inside of `catch()`.

Please consider merging this in. If you want to change the name of the option, that's cool. It's the functionality that I care about.

### CODE REVIEW

**Comment by graysonhicks** [comment]
Looks good, thanks!  Will get it merged and released asap.

**Comment by stevensacks** [comment]
@graysonhicks Just a quick reminder about this PR.

**Comment by stevensacks** [comment]
@graysonhicks My weekly reminder to please merge this in.

**Comment by graysonhicks** [comment]
@stevensacks Sorry for the delay, just released with `3.3.0`!

**Pull request merged**
