### PR TITLE
feat: add Gatsby CDN support

### PR DESCRIPTION
**Pull request by raae**

### CODE REVIEW

**Comment by graysonhicks** [comment]
Hey @raae is this okay to merge?  Should I pubilsh a canary version for you to test out?

**Comment by raae** [comment]
I'll have a look this weekend.

**Comment by raae** [comment]
Still missing array support, as creation of file nodes is duplicated in createNode (done) createNodes (not done).

**Comment by graysonhicks** [comment]
@raae Thanks!  Want to pair on this soon?

**Comment by aghreed** [comment]
@raae and @graysonhicks — I have a project that has a use for Image CDN supported remote images. Can I help move this PR across the finish line so we can test it out? Thanks!

**Review by aghreed — APPROVED** [review]
Don't know much about this, but LGTM. Would love to try this out with a site!

**Comment by graysonhicks** [comment]
@aghreed @raae Okay, I fixed the conflicts and published this as `3.6.0-alpha`!  Sounds like from raae's last comment there could be bugs with arrays or duplication, but should now be easier to test.  Let me know, thanks!

**Comment by aghreed** [comment]
Just pulled down the `3.6.0-alpha` to experiment with and looks like we had a bad merge conflict resolution. Notified @graysonhicks and we'll circle back to this soon to resolve.

**Comment by graysonhicks** [comment]
Closing this as the same work was merged in with #123 .  Thanks @raae !!!

**Pull request closed without merging**
