### PR TITLE
fix: support multiple image fields on one node type

### LINKED ISSUE #33: Impossible to add two image fields in the same node
In one of our projects we have a few nodes that (because reasons) have more than one field containing a remote image. The `gatsby-config.js` contains something like:

```
    {
      resolve: 'gatsby-plugin-remote-images',
      options: {
        nodeType: 'someNodeType',
        imagePath: 'introImage',
        name: 'localIntroImage',
      },
    },
    {
      resolve: 'gatsby-plugin-remote-images',
      options: {
        nodeType: 'someNodeType',
        imagePath: 'bodyImage',
        name: 'localBodyImage',
      },
    },
```
This setup worked fine until we updated to the latest (`2.0.0`) version. With the newer version there are no visible errors, but both the `localIntroImage` and `localBodyImage` in the `someNodeType` end up pointing to the same `FileNode` instance.

This happens because the plugin is storing a mapping `sourceNodeId -> generatedFileNodeId` in the `fileNodeMap` map. Obviously, this means that even though the plugin generates two different `FileNode`s with the proper downloaded files, the `createResolvers` api always returns whatever `FileNode` happened to have been generated last.

We temporarily solved this by using a custom version of the plugin where the keys in `fileNodeMap` are `${node.id}-${name}` instead of just `${node.id}`.

### PR DESCRIPTION
**Pull request by wKovacs64**
Closes #33

### CODE REVIEW

**Comment by wKovacs64** [comment]
Also survives cached rebuilds, now.

**Comment by graysonhicks** [comment]
Good stuff, thanks!

**Comment by wKovacs64** [comment]
Cool. You'll probably want to release a v2.0.1 that includes this fix for v2 folks.

**Comment by kpennell** [comment]
@graysonhicks Struggling here. I'm guessing we can't use two images on one node? ie this stopped working:
```

    {
      resolve: "gatsby-plugin-remote-images",
      options: {
        nodeType: "item",
        imagePath: "thumbnail",
        name: "optimized_thumbnail",
      },
    },
    {
      resolve: "gatsby-plugin-remote-images",
      options: {
        nodeType: "item",
        imagePath: "instructor_image",
        name: "optimized_instructor_image",
      },
    },
``` 

It only uses the latter item

**Comment by kpennell** [comment]
Yep, reverting to 1.0.7 fixed it! All good. Will wait.

**Comment by wKovacs64** [comment]
@kpennell Yeah, this fix didn't get released yet. Waiting on a v2.0.1 or whatever. Sorry for the hassle.

**Comment by kpennell** [comment]
@wKovacs64 no prob. great plugin.

**Pull request merged**
